### ISSUE TITLE
call button and question mark next to it needs a re-design

### ISSUE THREAD

**Issue by ali-tunahan** [dila0/google-solution-challenge-2023-bilkent#25]
Also add content to the question mark about:
1.How to use the call function
2.What is the safe word
3.Phone will vibrate if safe word is detected
4.Emergency contacts will receive an sms and current location
5.112 will be dialed
6.Mention that buttons on the call screen are just there to make the ui look realistic and only the end the call button works.
7.Mention if voice recog is disabled in the settings, this emergency call and sms can be done by clicking the button on the call screen

**Comment by atakanserifoglu** [comment]
Done.
